### ISSUE TITLE
Background and fill-color not working

### ISSUE THREAD

**Issue by txsmith** [OsmSharp/OsmSharp#140]
The MapCSS properties *background-color* and *fill-color* for the map canvas are parsed, but not rendered in iOS.

**Comment by xivk** [comment]
- Add a setting on Map to override the backcolor. 
- Add a setting on Layer to override the backcolor.

**Comment by vasgk** [comment]
Following the previous discussion (https://github.com/OsmSharp/OsmSharpDataProcessor/issues/11), I have also noticed that the BackColor of the LayerScene (in the files LayerScene.cs, Map.cs, MapCSSInterpreter.cs) has the correct value that I have used in the mapcss file.
However, when the map is rendering still has the  default canvas color (white background).
