### ISSUE TITLE
router based on a database

### ISSUE THREAD

**Issue by Lotto2** [OsmSharp/OsmSharp#210]
Hello,

first of all: OsmSharp is great work. 

My problem: Loading big osm.pbf-files takes a long time. i got 'out of memory'-errors with bigger files (500MB).

So i pulled a PBF-file in a PostgreSQL-database. i did not succeed in creating a router based on a database.

i can open a datasource like that:

IDataSourceReadOnly source = new OsmSharp.Data.PostgreSQL.Osm.PostgreSQLDataSource(con);

How do i create a router based on a database?

**Comment by xivk** [comment]
Creating a router based on a database is not a very good idea. You should be able to build in x64 and then process the data.

In the latests version there is also the option of using a memory-mapped file-based graph.
