### ISSUE TITLE
TileLayers on Mobile are blurry

### ISSUE THREAD

**Issue by Bonnoj** [OsmSharp/OsmSharp#213]
I'm exploring OsmSharp as it seems a great project for my goals, I've started exploring the examples and want to use TileLayers for my project. I've tried different sources for TileLayers (eg. osm) but they are rendered with really low quality, it feels like it's on the wrong zoomlevel.

I've attached an example on a 1024 x 600 resolution. On different devices it looks blurry like this.

![screen shot 2015-02-03 at 11 32 17](https://cloud.githubusercontent.com/assets/5849169/6018618/6199ad28-ab98-11e4-9c03-63fbbf09da57.png)

**Comment by xivk** [comment]
There is a scale factor for different devices, there may be a problemen related to that. Try setting the scale factor manually on the mapview...
