### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vherbst** [OsmSharp/OsmSharp#231]
I'm new to cross platform development with C# and  can't get the Demos running. I'm using Vs2012 prof. but the projects are shown as not compatible. The nuget packages should update themselves? How to get it to work?

**Comment by Lotto2** [comment]
Use VS2013 to open the projects. and yes, the nuget packages update themselves when compiling.

**Comment by xivk** [comment]
Yes, what @Lotto2 said.

**Comment by vherbst** [comment]
Thank you I will check this out. 

 

Von: Lotto2 [mailto:notifications@github.com] 
Gesendet: Montag, 27. April 2015 10:22
An: OsmSharp/OsmSharp
Cc: vherbst
Betreff: Re: [OsmSharp] Question (#231)

 

Use VS2013 to open the projects. and yes, the nuget packages update themselves when compiling.
