### ISSUE TITLE
Restrictions in Dykstra

### ISSUE THREAD

**Issue by VladimirDVV** [OsmSharp/OsmSharp#236]
When do you plan to make support restrictions in Dykstra.cs.

**Comment by xivk** [comment]
Support was there but in the current version it's disabled again due to a few problems. Fixing this is on the roadmap and should be done sometime during the next couple of months.

Feel free to try implementing this yourself, I can point you in the right direction if you want... :+1:

**Comment by hernansinc** [comment]
Hello,
First of all thank for the good job here :) ...currently I'm trying to use your wonderful library for a university project and I would like to know if there is a version that could support the turn restriction and turn-u restriction as well? I read the code of the release version but I realized that it's commented those lines.
Thanks for everything and your time.
Best Regards
Hernan

**Comment by xivk** [comment]
@hernansinc The routing-part of OsmSharp has move to a different project. Turn-restrictions are supported, check here:

https://github.com/itinero/routing

**Comment by xivk** [comment]
No announcement yet but your question was best answered by pointing to the new codebase. Release and announcement here is planned for July.
